{% set name = "infinity" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8daa7c15ce2100fdccfde212337e0cd5cf085869f54dc2634b6c30d61461ecda

build:
  noarch: python
  number: 1
  script:  {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  imports:
    - infinity
  commands:
    - pip check
  requires: 
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kvesteri/infinity
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: 'All-in-one infinity value for Python. Can be compared to any object.'
  dev_url: https://github.com/kvesteri/infinity
  doc_url: https://github.com/kvesteri/infinity

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
