{% set name = "infinity" %}
{% set version = "1.5" %}
{% set bundle = "tar.gz" %}
{% set hash = "8daa7c15ce2100fdccfde212337e0cd5cf085869f54dc2634b6c30d61461ecda" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - infinity

about:
  home: https://github.com/kvesteri/infinity
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: All-in-one infinity value for Python. Can be compared to any object.
  dev_url: https://github.com/kvesteri/infinity
  doc_url: https://github.com/kvesteri/infinity

extra:
  recipe-maintainers:
    - pmlandwehr
